env_name = [
            'SafeMetaDrive-easydense',      # 0
            'SafeMetaDrive-easymean',       # 1
            'SafeMetaDrive-easysparse',     # 2
            'SafeMetaDrive-mediumdense',    # 3
            'SafeMetaDrive-mediummean',     # 4
            'SafeMetaDrive-mediumsparse',   # 5
            'SafeMetaDrive-harddense',      # 6
            'SafeMetaDrive-hardmean',       # 7
            'SafeMetaDrive-hardsparse',     # 8
            'SafetyCarCircle',              # 9
            'SafetyAntCircle',              # 10
            'SafetyAntRun',                 # 11
            'SafetyAntVelocityGymnasium',   # 12
            'SafetyBallCircle',             # 13
            'SafetyBallRun',                # 14
            'SafetyCarButton1Gymnasium',    # 15
            'SafetyCarButton2Gymnasium',    # 16
            'SafetyCarCircle1Gymnasium',    # 17
            'SafetyCarCircle2Gymnasium',    # 18
            'SafetyCarGoal1Gymnasium',      # 19
            'SafetyCarGoal2Gymnasium',      # 20
            'SafetyCarPush1Gymnasium',      # 21
            'SafetyCarPush2Gymnasium',      # 22
            'SafetyCarRun',                 # 23
            'SafetyDroneCircle',            # 24
            'SafetyDroneRun',               # 25
            'SafetyHalfCheetahVelocityGymnasium', # 26
            'SafetyHopperVelocityGymnasium',      # 27
            'SafetyPointButton1Gymnasium',        # 28
            'SafetyPointButton2Gymnasium',        # 29
            'SafetyPointCircle1Gymnasium',        # 30
            'SafetyPointCircle2Gymnasium',        # 31
            'SafetyPointGoal1Gymnasium',          # 32
            'SafetyPointGoal2Gymnasium',          # 33
            'SafetyPointPush1Gymnasium',          # 34
            'SafetyPointPush2Gymnasium',          # 35
            'SafetySwimmerVelocityGymnasium',     # 36
            'SafetyWalker2dVelocityGymnasium']    # 37